version: '2'

services:
  mail:
    image: tvial/docker-mailserver:v2
    # build: .
    hostname: mail
    domainname: dockie.me
    volumes:
     - maildata:/var/mail
    volumes:
     - ./config/:/tmp/docker-mailserver/
     - ./config/opendkim/:/tmp/docker-mailserver/opendkim/
    environment:
      MAIL_USER: rubberduck@duckie.me
      MAIL_PASS: pass

  data:
    image: mongo
    restart: always

  core:
    image: lucardo/rubberduckapi
    links:
     - "mail:mail"
     - "data:mongodb"
    restart: always
    ports:
     - "80:80"
    environment:
     NODE_TLS_REJECT_UNAUTHORIZED: 0
     MAIL_USER: rubberduck@duckie.me
     MAIL_PASS: pass

volumes:
  maildata:
    driver: local